import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import vm from 'node:vm';

const script=readFileSync(new URL('../public/site.js',import.meta.url),'utf8');
const context=vm.createContext({
  document:{querySelectorAll:()=>[],querySelector:()=>null,getElementById:()=>null},
});
vm.runInContext(script,context);
const classify=(group,text,alt)=>vm.runInContext(`altBul(${JSON.stringify(group)},${JSON.stringify(text)},${JSON.stringify(alt)}).id`,context);
assert.equal(vm.runInContext('GRUPLAR.map(x=>x.g).join(",")',context),'A,B,C,D,E,F');
assert.equal(vm.runInContext('GRUPLAR.map(x=>x.ad).join("|")',context),'Temizlik Kâğıtları|Sıvı Temizlik Ürünleri|Aparatlar ve Ekipmanlar|Temizlik Sarf Ürünleri|Gıda ve Atıştırmalıklar|Kırtasiye ve Ofis Sarf Ürünleri');
assert.equal(vm.runInContext('Object.keys(ALTLAR).length',context),6);
assert.equal(vm.runInContext('VITRIN_GRUPLAR.join(",")',context),'A,B,C,D,E,F');
assert.equal(vm.runInContext('ALTLAR.F.length',context),5);
assert.equal(vm.runInContext('ALTLAR.C[3].id',context),'C4');
assert.equal(vm.runInContext('ALTLAR.A[0].gorsel',context),'/img/products/daire-havlu-pecete.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.A[1].gorsel',context),'/img/products/daire-islak-havlu.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.A[2].gorsel',context),'/img/products/daire-tuvalet-kagidi.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-havlu-pecete.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/products/daire-islak-havlu.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/products/daire-tuvalet-kagidi.webp',import.meta.url)));
assert.equal(vm.runInContext('GRUP_FOTO.A',context),'/img/products/daire-temizlik-kagitlari.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-temizlik-kagitlari.webp',import.meta.url)));
assert.equal(vm.runInContext('GRUP_FOTO.B',context),'/img/products/daire-sivi-temizlik.webp?v=3');
assert.ok(existsSync(new URL('../public/img/products/daire-sivi-temizlik.webp',import.meta.url)));
assert.equal(vm.runInContext('ALTLAR.B[0].gorsel',context),'/img/products/daire-endustriyel-sivi.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-endustriyel-sivi.webp',import.meta.url)));
assert.equal(vm.runInContext('ALTLAR.B[1].gorsel',context),'/img/products/daire-genel-temizlik.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-genel-temizlik.webp',import.meta.url)));
assert.equal(vm.runInContext('GRUP_FOTO.C',context),'/img/products/daire-aparat-ekipman.webp?v=4');
assert.ok(existsSync(new URL('../public/img/products/daire-aparat-ekipman.webp',import.meta.url)));
assert.equal(vm.runInContext('ALTLAR.C[0].gorsel',context),'/img/products/daire-havlu-aparat.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.C[1].gorsel',context),'/img/products/daire-sabun-aparat.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.C[2].gorsel',context),'/img/products/daire-cop-kovasi.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.C[3].gorsel',context),'/img/products/daire-mop-aparat.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-havlu-aparat.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/products/daire-sabun-aparat.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/products/daire-cop-kovasi.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/products/daire-mop-aparat.webp',import.meta.url)));
assert.equal(vm.runInContext('ALTLAR.D[0].gorsel',context),'/img/products/daire-cop-poseti.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.D[1].gorsel',context),'/img/products/daire-sarf.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.D[2].gorsel',context),'/img/products/daire-kullan-at.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.E[0].gorsel',context),'/img/products/daire-cay-seker.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.E[1].gorsel',context),'/img/products/daire-kahve.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.E[2].gorsel',context),'/img/products/daire-icecek.webp?v=2');
assert.equal(vm.runInContext('ALTLAR.E[3].gorsel',context),'/img/products/daire-atistirmalik.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-cop-poseti.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/products/daire-sarf.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/koroplast.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/caykur.webp',import.meta.url)));
assert.equal(vm.runInContext('GRUP_FOTO.D',context),'/img/products/daire-temizlik.webp?v=4');
assert.ok(existsSync(new URL('../public/img/products/daire-temizlik.webp',import.meta.url)));
assert.equal(vm.runInContext('GRUP_FOTO.E',context),'/img/products/daire-gida-ikram.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-gida-ikram.webp',import.meta.url)));
assert.equal(vm.runInContext('ALTLAR.F[0].gorsel',context),'/img/products/daire-kalem-yazi.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-kalem-yazi.webp',import.meta.url)));
assert.equal(vm.runInContext('ALTLAR.F[1].gorsel',context),'/img/products/daire-masaustu.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-masaustu.webp',import.meta.url)));
assert.equal(vm.runInContext('ALTLAR.F[2].gorsel',context),'/img/products/daire-dosya-arsiv.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-dosya-arsiv.webp',import.meta.url)));
assert.equal(vm.runInContext('ALTLAR.F[3].gorsel',context),'/img/products/daire-ambalaj.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-ambalaj.webp',import.meta.url)));
assert.equal(vm.runInContext('ALTLAR.F[4].gorsel',context),'/img/products/daire-bilgisayar.webp?v=2');
assert.ok(existsSync(new URL('../public/img/products/daire-bilgisayar.webp',import.meta.url)));
assert.equal(vm.runInContext('GRUP_FOTO.F',context),'/img/products/daire-kirtasiye-ofis.webp?v=3');
assert.ok(existsSync(new URL('../public/img/products/daire-kirtasiye-ofis.webp',import.meta.url)));
assert.ok(vm.runInContext('POPULER_MARKALAR.B.some(x=>x.ad==="Yumoş")',context));
assert.equal(vm.runInContext('POPULER_MARKALAR.B.map(x=>x.ad).join(",")',context),'Yumoş,Vernel,Ozopak,Fairy,Domestos,Cif,Pril,Finish,Asperox,Porçöz');
assert.equal(vm.runInContext('POPULER_MARKALAR.D.map(x=>x.ad).join(",")',context),'Koroplast,Parex,Ceymop,Ozopak,Vileda,Scotch-Brite');
assert.equal(vm.runInContext('POPULER_MARKALAR.E.map(x=>x.ad).join(",")',context),'Eti,Lipton,Nestlé,Pınar,Erikli,Ülker,Çaykur,Doğuş,Mehmet Efendi');
assert.ok(vm.runInContext('POPULER_MARKALAR.E.some(x=>x.ad==="Eti")',context));
assert.ok(vm.runInContext('POPULER_MARKALAR.A.some(x=>x.ad==="Espiga")',context));
assert.equal(vm.runInContext('POPULER_MARKALAR.A.map(x=>x.ad).join(",")',context),'Espiga,Selpak,Belinno,Sleepy,Papia,Solo,Familia,Polente,DeepFresh,Freshmaker,Komili,Teno,Rulopak');
assert.equal(vm.runInContext('POPULER_MARKALAR.C.map(x=>x.ad).join(",")',context),'Vileda,Parex,Palex,Vialli,Flosoft,Scotch-Brite');
assert.ok(vm.runInContext('POPULER_MARKALAR.F.some(x=>x.ad==="Faber-Castell")',context));
assert.ok(vm.runInContext('POPULER_MARKALAR.F.some(x=>x.ad==="Logitech")',context));
assert.ok(existsSync(new URL('../public/img/brands/uniball.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/noki.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/belinno.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/polente.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/pril.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/finish.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/asperox.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/scotchbrite.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/yumos.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/lipton.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/tork.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/canon.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/logitech.webp',import.meta.url)));
assert.ok(existsSync(new URL('../public/img/brands/spigen.webp',import.meta.url)));
assert.match(readFileSync(new URL('../public/urunler.html',import.meta.url),'utf8'),/id="populer-markalar"/);
assert.match(readFileSync(new URL('../public/catalog-ui.js',import.meta.url),'utf8'),/populer-markalar/);
assert.match(readFileSync(new URL('../public/catalog-ui.js',import.meta.url),'utf8'),/s\.gorsel \|\| grupFoto/);
assert.equal(vm.runInContext('Object.keys(MARKA_TERCIHLERI).join(",")',context),'C1');
assert.equal(classify('A','Islak havlu 90’lı'),'diger');
assert.equal(classify('A','Islak havlu 90’lı','A2'),'A2');
assert.equal(vm.runInContext('gecerliG("Hijyen")',context),'A');
assert.equal(vm.runInContext('gecerliA("cop-posetleri")',context),'D1');
assert.equal(vm.runInContext('gecerliG("Temizlik","cop-posetleri")',context),'D');
assert.equal(vm.runInContext('urunAdiYazi("Sıvı el sabunu 1 L · 1 litre pompalı şişe")',context),'Sıvı El Sabunu 1 L · 1 Litre Pompalı Şişe');
assert.equal(vm.runInContext('olcuYazi("4")',context),'4');
assert.equal(vm.runInContext('olcuYazi("2,5")',context),'2,5');
assert.equal(vm.runInContext('olcuYazi("400")',context),'400');
assert.equal(vm.runInContext('olcuYazi("21 santimetre")',context),'21 cm');
assert.equal(vm.runInContext('olcuYazi("750 mililitre")',context),'750 ml');
assert.equal(vm.runInContext('olcuYazi("3,2 litre")',context),'3,2 L');
assert.equal(vm.runInContext('olcuYazi("5 kilogram")',context),'5 kg');
assert.equal(vm.runInContext('olcuYazi("30 × 45")',context),'30 × 45');
assert.equal(vm.runInContext('olcuYazi("40 gr.")',context),'40 g');
assert.equal(vm.runInContext('olcuYazi("125 gr")',context),'125 g');
assert.equal(vm.runInContext('olcuYazi("1 kg")',context),'1 kg');
assert.equal(vm.runInContext('olcuYazi("250 ml")',context),'250 ml');
assert.equal(vm.runInContext('olcuYazi("1000 ml")',context),'1000 ml');
assert.equal(vm.runInContext('olcuYazi("51MM")',context),'51 mm');
assert.equal(vm.runInContext(`markaTercihSatir(${JSON.stringify('Islak havlu 90’lı')},${JSON.stringify('Espiga')})`,context),'Islak havlu 90’lı · Marka tercihi: Espiga');
assert.equal(vm.runInContext(`markaTercihSatir(${JSON.stringify('Islak havlu 90’lı')},${JSON.stringify('Fark etmez')})`,context),'Islak havlu 90’lı · Marka tercihi: fark etmez');

const data=JSON.parse(readFileSync(new URL('../public/katalog.json',import.meta.url),'utf8'));
assert.equal(data.gruplar.join(','),'A,B,C,D,E,F');
assert.match(readFileSync(new URL('../public/urunler.html',import.meta.url),'utf8'),/class="cat-bar"/);
assert.ok(!readFileSync(new URL('../public/urunler.html',import.meta.url),'utf8').includes('cat-rail'));
const ALTLAR_IDS={
  A:['A1','A2','A3'],
  B:['B1','B2'],
  C:['C1','C2','C3','C4'],
  D:['D1','D2','D3'],
  E:['E1','E2','E3','E4'],
  F:['F1','F2','F3','F4','F5'],
};
assert.equal(data.urunler.length,448);
assert.equal(data.kategoriler.map((k)=>k.id).join(","),"A,B,C,D,E,F");
assert.equal(data.kategoriler[2].altlar.map((a)=>a.id).join(","),"C1,C2,C3,C4");
assert.equal(data.kategoriler.find((k)=>k.id==='F').altlar.find((a)=>a.id==='F2').gorsel,'/img/products/daire-masaustu.webp?v=2');
assert.equal(data.kategoriler.find((k)=>k.id==='F').altlar.find((a)=>a.id==='F3').gorsel,'/img/products/daire-dosya-arsiv.webp?v=2');
assert.equal(data.kategoriler.find((k)=>k.id==='F').altlar.find((a)=>a.id==='F5').gorsel,'/img/products/daire-bilgisayar.webp?v=2');
assert.ok(!JSON.stringify(data).includes('"fiyat"'));
assert.ok(data.urunler.every((row)=>['A','B','C','D','E','F'].includes(row.kategori)));
assert.equal(data.urunler.filter((row)=>row.alt==='E1').length,17);
assert.equal(data.urunler.filter((row)=>row.alt==='E2').length,21);
assert.equal(data.urunler.filter((row)=>row.alt==='E3').length,25);
assert.equal(data.urunler.filter((row)=>row.alt==='E4').length,20);
assert.equal(data.urunler.filter((row)=>row.kategori==='F').length,152);
assert.equal(data.urunler.filter((row)=>row.alt==='F1').length,33);
assert.equal(data.urunler.filter((row)=>row.alt==='F2').length,44);
assert.equal(data.urunler.filter((row)=>row.alt==='F3').length,28);
assert.equal(data.urunler.filter((row)=>row.alt==='F4').length,13);
assert.equal(data.urunler.filter((row)=>row.alt==='F5').length,34);
assert.equal(data.urunler.find((row)=>row.ad==='Kablolu Klavye').marka,'Lecoo');
assert.equal(data.urunler.find((row)=>row.marka==='Philips' && row.ad==='Kablosuz Klavye Mouse Seti').renk,'Siyah');
assert.equal(data.urunler.find((row)=>row.marka==='Lecoo' && row.ad==='Kablolu Mouse').urunTuru,'USB');
assert.equal(data.urunler.find((row)=>row.marka==='ASUS' && row.ad==='Kablosuz Mouse').renk,'Siyah');
assert.equal(data.urunler.find((row)=>row.marka==='Kodak' && row.ad==='USB-C Şarj Kablosu').olcu,'1M');
assert.equal(data.urunler.find((row)=>row.marka==='Kensington' && row.renk==='Kırmızı').ad,'Jel Mouse Pad');
assert.ok(data.urunler.filter((row)=>row.alt==='F5').every((row)=>row.gorselTuru==='urun'));
assert.equal(data.urunler.filter((row)=>row.ad==='Zooo Plastik Kaplı Ataş').length,3);
assert.equal(data.urunler.filter((row)=>row.marka==='Panfix' && row.ad==='Şeffaf Bant').length,2);
assert.equal(data.urunler.find((row)=>row.marka==='MAS' && row.ad==='Koli Bandı').alt,'F4');
assert.equal(data.urunler.find((row)=>row.ad==='Koli Bant Makinesi').marka,'MAS');
assert.equal(data.urunler.find((row)=>row.ad==='Hava Kabarcıklı Torba Zarf' && row.olcu==='26 × 35').marka,'Oyal');
assert.equal(data.urunler.find((row)=>row.marka==='Noki' && row.ad==='Şeffaf Bant').olcu,'12 × 33M');
assert.equal(data.urunler.find((row)=>row.ad==='Çift Taraflı Bant').olcu,'12 × 25M');
assert.equal(data.urunler.find((row)=>row.marka==='MAS' && row.ad==='Koli Bandı').olcu,'45Mm × 40M');
assert.ok(data.urunler.some((row)=>row.ad==='Mini Bant Kesici + Şeffaf Bant'));
assert.equal(data.urunler.find((row)=>row.ad==='Bant Kesici Flash Büyük').renk,'Siyah');
assert.equal(data.urunler.find((row)=>row.ad==='Thermo Deri Özel Kesim Ajanda').olcu,'2026');
assert.equal(data.urunler.find((row)=>row.ad==='Cilt Bezli Çizgili Ajanda').olcu,'17 × 24');
assert.equal(data.urunler.find((row)=>row.marka==='Gıpta' && row.ad==='Eko Günlük Kareli Ajanda').kapasite,'2026');
assert.equal(data.urunler.find((row)=>row.ad==='Laminasyon Poşeti').ambalajAdedi,"100'lü");
assert.equal(data.urunler.find((row)=>row.ad==='Para Kontrol Kalemi').alt,'F1');
assert.equal(data.urunler.filter((row)=>row.marka==='Pensan' && row.ad==='Tükenmez Kalem').length,3);
assert.equal(data.urunler.filter((row)=>row.marka==='Edding' && row.ad==='Tahta Kalemi').length,4);
assert.equal(data.urunler.filter((row)=>row.marka==='Faber-Castell' && row.ad==='Asetat Kalem').length,3);
assert.equal(data.urunler.find((row)=>row.ad==='Kalem Ucu').olcu,'0,7Mm');
assert.equal(data.urunler.find((row)=>row.ad==='Kalem Ucu').kapasite,'2B');
assert.ok(data.urunler.filter((row)=>row.alt==='F1').every((row)=>row.gorselTuru==='urun'));
assert.equal(data.urunler.filter((row)=>row.marka==='MAS' && row.ad==='Zımba Makinesi').length,2);
assert.equal(data.urunler.filter((row)=>row.marka==='MAS' && row.ad==='Zımba Teli').length,2);
assert.equal(data.urunler.find((row)=>row.ad==='Delgeç').kapasite,'25 Sayfa');
assert.equal(data.urunler.find((row)=>row.ad==='Makas').olcu,'17,8Cm');
assert.equal(data.urunler.find((row)=>row.ad==='Tel Sökücü').marka,'Leitz');
assert.equal(data.urunler.filter((row)=>row.marka==='MAS' && row.ad==='Istampa').length,2);
assert.equal(data.urunler.find((row)=>row.ad==='Escrito Maputo İmha Makinesi').urunTuru,'Ofis Tipi');
assert.equal(data.urunler.find((row)=>row.marka==='Post-it' && row.ad==='Yapışkan Not').olcu,'76 × 76Mm');
assert.equal(data.urunler.find((row)=>row.marka==='Pritt' && row.ad==='Stick Yapıştırıcı').olcu,'22Gr');
assert.equal(data.urunler.find((row)=>row.marka==='Casio' && row.ad==='Hesap Makinesi').olcu,'12 Hane');
assert.equal(data.urunler.filter((row)=>row.marka==='Esselte' && row.ad==='Telli Dosya').length,1);
assert.equal(data.urunler.filter((row)=>row.ad==='Klasör' && row.marka==='Noki').length,2);
assert.equal(data.urunler.filter((row)=>row.ad==='Separatör' && row.marka==='Noki').length,4);
assert.equal(data.urunler.filter((row)=>row.ad==='Sekreterlik').length,1);
assert.equal(data.urunler.find((row)=>row.ad==='Sekreterlik').marka,'Noki');
assert.ok(!data.urunler.some((row)=>row.marka==='Kraf'));
assert.equal(data.urunler.filter((row)=>row.marka==='Noki' && row.ad==='Telli Dosya Eco').length,3);
assert.equal(data.urunler.find((row)=>row.ad==='Arşiv Kutusu').marka,'Leitz');
assert.equal(data.urunler.find((row)=>row.ad==='Körüklü Dosya').urunTuru,'5 Bölmeli');
assert.ok(!data.urunler.some((row)=>row.marka==='Dilman'));
assert.ok(!data.urunler.some((row)=>row.ad==='İmza Dosyası'));
assert.ok(!data.urunler.some((row)=>row.ad==='4 Halkalı Dosya'));
assert.equal(data.urunler.find((row)=>row.ad==='2 Halkalı Dosya').marka,'Noki');
assert.equal(data.urunler.find((row)=>row.ad==='Separatör' && row.olcu==='1-20').gorsel,'/img/products/noki-separator-120.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Esselte' && row.ad==='Klasör' && row.renk==='Kırmızı').urunTuru,'Geniş');
assert.ok(data.urunler.filter((row)=>row.alt==='F3').every((row)=>row.gorselTuru==='urun'));
assert.equal(data.urunler.filter((row)=>row.alt==='A1').length,13);
assert.equal(data.urunler.find((row)=>row.id==='p-005').marka,'Belinno');
assert.equal(data.urunler.find((row)=>row.ad==='Hareketli Havlu Kağıdı').urunTuru,'Professional');
assert.equal(data.urunler.find((row)=>row.id==='p-003').urunTuru,'Eko');
assert.equal(data.urunler.find((row)=>row.ad==='Dispenser Peçete').marka,'Espiga');
assert.equal(data.urunler.find((row)=>row.ad==='Peçete' && row.marka==='Solo').ambalajAdedi,"100'lü");
assert.equal(data.urunler.find((row)=>row.marka==='Belinno' && row.ad==='Z Peçete').ambalajAdedi,"150'li");
assert.equal(data.urunler.find((row)=>row.marka==='Belinno' && row.ad==='Z Peçete').urunTuru,"12'li Koli");
assert.equal(data.urunler.find((row)=>row.marka==='Belinno' && row.ad==='Z Peçete').gorsel,'/img/products/belinno-z-pecete.webp');
assert.ok(existsSync(new URL('../public/img/products/belinno-z-pecete.webp',import.meta.url)));
assert.ok(!data.urunler.some((row)=>row.marka==='Belinno' && /200'lü|300'lü/.test(row.ambalajAdedi)));
assert.ok(!data.urunler.some((row)=>row.id==='p-327'));
assert.ok(!data.urunler.some((row)=>row.alt==='A1' && row.marka==='Bellino'));
assert.ok(data.urunler.filter((row)=>row.alt==='A1').every((row)=>row.gorselTuru==='urun'));
assert.ok(data.urunler.filter((row)=>row.kategori==='C').every((row)=>row.gorselTuru==='urun'));
assert.equal(data.urunler.find((row)=>row.id==='p-128').marka,'Palex');
assert.equal(data.urunler.find((row)=>row.id==='p-128').gorsel,'/img/products/palex-z-havlu.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-145').gorsel,'/img/products/palex-sensor-sivi.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-148').marka,'Palex');
assert.equal(data.urunler.filter((row)=>row.alt==='A2').length,16);
assert.equal(data.urunler.find((row)=>row.ad==='Kişisel Bakım Havlusu').marka,'Sleepy');
assert.equal(data.urunler.find((row)=>row.marka==='Polente' && row.ad==='Islak Havlu').ambalajAdedi,"100'lü");
assert.equal(data.urunler.find((row)=>row.marka==='Familia' && row.urunTuru==='Mineralin İyiliği').ambalajAdedi,"90'lı");
assert.equal(data.urunler.filter((row)=>row.alt==='A2' && row.marka==='Familia').length,3);
assert.equal(data.urunler.find((row)=>row.marka==='Familia' && row.urunTuru==='Lavantanın Ferahlığı').gorsel,'/img/products/familia-islak-havlu-lavanta.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Sleepy' && row.urunTuru==='Herbal Lavanta').gorsel,'/img/products/sleepy-herbal-lavanta.webp');
assert.ok(!data.urunler.some((row)=>row.marka==='Sleepy' && row.urunTuru==='Easy Clean'));
assert.equal(data.urunler.find((row)=>row.marka==='DeepFresh' && row.ad==='Antibakteriyel Islak Mendil').ambalajAdedi,"100'lü");
assert.ok(!data.urunler.some((row)=>row.marka==='DeepFresh' && row.ad==='Yüzey Temizlik Havlusu'));
assert.equal(data.urunler.find((row)=>row.marka==='DeepFresh' && row.urunTuru==='Maxi Lavanta').ambalajAdedi,"1444'lü");
assert.equal(data.urunler.find((row)=>row.marka==='DeepFresh' && row.urunTuru==='Zeytinyağlı').ambalajAdedi,"120'li");
assert.equal(data.urunler.find((row)=>row.marka==='Freshmaker' && row.ad==='Yüzey Temizlik Havlusu').ambalajAdedi,"50'li");
assert.equal(data.urunler.find((row)=>row.marka==='Komili' && row.ad==='Islak Temizlik Havlusu').ambalajAdedi,"90'lı");
assert.equal(data.urunler.find((row)=>row.ad==='Metal Çöp Konteyneri' && row.kapasite==='800Lt').gorsel,'/img/products/metal-konteyner-800.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Çöp Konteyneri' && row.kapasite==='80Lt').gorsel,'/img/products/plastik-konteyner-80.webp');
assert.equal(data.urunler.find((row)=>row.marka==='MAS' && row.ad==='Masa Altı Çöp Kovası').gorsel,'/img/products/mas-masa-alti.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Pedallı Çöp Kovası' && !row.marka).gorsel,'/img/products/plastik-pedalli.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Sallanır Kapaklı Çöp Kovası' && !row.marka).gorsel,'/img/products/plastik-sallanir.webp');
assert.equal(data.urunler.filter((row)=>row.alt==='C3').length,9);
assert.equal(data.urunler.find((row)=>row.id==='p-439').ad,'Kolon Küllük');
assert.equal(data.urunler.find((row)=>row.id==='p-439').marka,'Palex');
assert.equal(data.urunler.find((row)=>row.id==='p-439').gorsel,'/img/products/palex-kolon-kulluk.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-440').ad,'Bahçe Tipi Çöp Kovası');
assert.equal(data.urunler.find((row)=>row.id==='p-440').marka,'Palex');
assert.equal(data.urunler.find((row)=>row.id==='p-440').gorsel,'/img/products/palex-bahce-cop-kovasi.webp');
assert.ok(!data.urunler.some((row)=>row.alt==='C3' && /800 Litrelik|120 Litrelik|240 Litrelik|Pratik Kapaklı/.test(row.ad)));
assert.ok(!data.urunler.some((row)=>row.ad==='Pedallı Çöp Kovası' && row.marka==='Palex' && row.malzeme==='Plastik'));
assert.ok(!data.urunler.some((row)=>row.alt==='A2' && row.marka==='Selpak'));
assert.ok(data.urunler.filter((row)=>row.alt==='A2').every((row)=>row.gorselTuru==='urun'));
assert.equal(data.urunler.filter((row)=>row.alt==='A3').length,15);
assert.equal(data.urunler.find((row)=>row.id==='p-012').gorsel,'/img/products/espiga-mini-jumbo-tuvalet.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Papia' && row.ad==='Tuvalet Kağıdı').ambalajAdedi,"32'li");
assert.ok(!data.urunler.some((row)=>row.alt==='A3' && row.marka==='Bellino'));
assert.ok(data.urunler.filter((row)=>row.alt==='A3').every((row)=>row.gorselTuru==='urun'));
assert.equal(data.urunler.find((row)=>row.marka==='MAS' && row.ad==='Omega Kıskaç' && row.olcu==='51Mm').olcu,'51Mm');
assert.equal(data.urunler.find((row)=>row.marka==='MAS' && row.ad==='Omega Kıskaç' && row.olcu==='32Mm').ambalajAdedi,"12'li");
assert.equal(data.urunler.find((row)=>row.marka==='MAS' && row.ad==='Toplu İğne').kapasite,'20Gr');
assert.equal(data.urunler.find((row)=>row.marka==='Rio' && row.ad==='Renkli Harita Çivisi').urunTuru,'Silindirik');
assert.equal(data.urunler.find((row)=>row.marka==='MAS').gorselTuru,'urun');
assert.equal(data.urunler.find((row)=>row.marka==='Ülker' && row.ad==='Halley Çikolata Kaplı Bisküvi').ambalajAdedi,"24'lü");
assert.equal(data.urunler.find((row)=>row.marka==='Fellas' && row.ad==='Meyve Bar - Duble Kakaolu').olcu,'35Gr');
assert.equal(data.urunler.find((row)=>row.marka==='Eti' && row.ad==='Lifalif Bitter Çikolatalı Bar').olcu,'35Gr');
assert.equal(data.urunler.find((row)=>row.marka==='Ülker' && row.ad==='Çubuk Kraker').ambalajAdedi,"36'lı");
assert.equal(data.urunler.find((row)=>row.marka==='Eti' && row.ad==='Topkek Kakaolu').ambalajAdedi,"24'lü");
assert.equal(data.urunler.find((row)=>row.marka==='Eti' && row.ad==='Browni Çikolata Fındıklı Kek').ambalajAdedi,"20'li");
assert.ok(data.urunler.filter((row)=>row.marka==='Eti' && row.ad.startsWith('Lifalif')).every((row)=>row.ambalajAdedi==="12'li"));
assert.equal(data.urunler.find((row)=>row.marka==='Sırmakeş' && row.ad==='Su').olcu,'0,5Lt');
assert.equal(data.urunler.find((row)=>row.ad==='Bardak Su').ambalajAdedi,"12'li");
assert.equal(data.urunler.find((row)=>row.marka==='Nescafe' && row.ad==='Gold' && row.olcu==='900Gr').olcu,'900Gr');
assert.equal(data.urunler.find((row)=>row.marka==='Coffee Mate' && row.olcu==='500Gr').gorsel,'/img/products/coffee-mate-500.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Tchibo' && row.ad==='Espresso Sicilia Style').gorsel,'/img/products/tchibo-sicilia-1000.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Nescafe' && row.ad==='Sütlü Köpüklü').gorsel,'/img/products/nescafe-3u1-sutlu-kopuklu.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Coca Cola' && row.olcu==='250ML').ambalajAdedi,"24'lü");
assert.equal(data.urunler.find((row)=>row.marka==='Pınar' && row.ad==='Süt Laktozsuz').olcu,'1000ML');
assert.equal(data.urunler.find((row)=>row.marka==='Doğuş' && row.ad==='Earl Grey Demlik Çay').ambalajAdedi,"100'lü");
assert.equal(data.urunler.find((row)=>row.marka==='Doğuş' && row.ad==='Earl Grey Demlik Çay').gorsel,'/img/products/dogus-earl-grey-demlik.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Doğuş' && row.ad==='Karadeniz Demlik Çay').gorsel,'/img/products/dogus-karadeniz-demlik.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Doğuş' && row.ad==='Karadeniz Bardak Çay').gorsel,'/img/products/dogus-karadeniz-bardak.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Doğuş' && row.ad==='Karadeniz Çay' && row.olcu==='1Kg').gorsel,'/img/products/dogus-karadeniz-1kg.webp');
assert.ok(!data.urunler.some((row)=>row.marka==='Doğuş' && row.ad==='Filiz Çay'));
assert.ok(!data.urunler.some((row)=>row.marka==='Doğuş' && row.ad==='Tomurcuk Çay'));
assert.equal(data.urunler.find((row)=>row.marka==='Lipton' && row.ad==='Demlik Çay').gorsel,'/img/products/lipton-demlik.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Lipton' && row.ad==='Bardak Çay').gorsel,'/img/products/lipton-bardak.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Lipton' && row.ad==='Earl Grey Demlik Çay').gorsel,'/img/products/lipton-earl-grey.webp');
assert.ok(!data.urunler.some((row)=>row.ad==='Early Grey Demlik Çay'));
assert.equal(data.urunler.find((row)=>row.marka==='Çaykur' && row.ad==='Tiryaki Çay').olcu,'1Kg');
assert.equal(data.urunler.find((row)=>row.marka==='Çaykur' && row.ad==='Tiryaki Çay').gorsel,'/img/products/caykur-tiryaki.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Çaykur' && row.ad==='Turist Çay').gorsel,'/img/products/caykur-turist.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Çaykur' && row.ad==='Filiz Çay').gorsel,'/img/products/caykur-filiz.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Çaykur' && row.ad==='Tomurcuk Çay').olcu,'200Gr');
assert.equal(data.urunler.find((row)=>row.marka==='Çaykur' && row.ad==='Tomurcuk Çay').gorsel,'/img/products/caykur-tomurcuk.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Doğuş' && row.ad==='Jumbo Demlik Çay').olcu,'40Gr');
assert.equal(data.urunler.find((row)=>row.marka==='Doğuş' && row.ad==='Jumbo Demlik Çay').ambalajAdedi,"25'li");
assert.equal(data.urunler.find((row)=>row.marka==='Doğuş' && row.ad==='Jumbo Demlik Çay').gorsel,'/img/products/dogus-jumbo-demlik.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Balküpü' && row.olcu==='1Kg').gorsel,'/img/products/balkupu-1kg.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Balküpü' && row.olcu==='5Kg').gorsel,'/img/products/balkupu-5kg.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Balküpü' && row.olcu==='5Kg').urunTuru,'Dökme');
assert.equal(data.urunler.find((row)=>row.marka==='Irmak' && row.ad==='Küp Şeker').gorsel,'/img/products/irmak-seker-1kg.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Tek Sargılı Küp Şeker').marka,'Irmak');
assert.equal(data.urunler.find((row)=>row.ad==='Tek Sargılı Küp Şeker').olcu,'5Kg');
assert.equal(data.urunler.find((row)=>row.ad==='Tek Sargılı Küp Şeker').urunTuru,'Dökme');
assert.equal(data.urunler.find((row)=>row.ad==='Tek Sargılı Küp Şeker').gorsel,'/img/products/irmak-tek-sargili.webp');
assert.ok(!data.urunler.some((row)=>row.ad==='Tek Sargılı Şeker'));
assert.equal(data.urunler.find((row)=>row.ad==='Stick Toz Şeker').marka,'Irmak');
assert.equal(data.urunler.find((row)=>row.ad==='Stick Toz Şeker').olcu,'');
assert.equal(data.urunler.find((row)=>row.ad==='Stick Toz Şeker').gorsel,'/img/products/irmak-stick.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Nescafe' && row.ad==='Gold' && row.olcu==='900Gr').gorsel,'/img/products/nescafe-gold-900.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-186').ad,"2'si 1 Arada");
assert.equal(data.urunler.find((row)=>row.id==='p-186').gorsel,'/img/products/nescafe-2si1.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-190').gorsel,'/img/products/sirma-maden.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-191').gorsel,'/img/products/sirma-meyveli.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-191').urunTuru,'Limon Aromalı');
assert.equal(data.urunler.find((row)=>row.id==='p-200').gorsel,'/img/products/cappy-visne.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-199').gorsel,'/img/products/cappy-karisik.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-450').ad,'Zero');
assert.equal(data.urunler.find((row)=>row.id==='p-450').olcu,'330ML');
assert.equal(data.urunler.find((row)=>row.id==='p-451').olcu,'250ML');
assert.equal(data.urunler.find((row)=>row.id==='p-456').ad,'Coca Cola');
assert.equal(data.urunler.find((row)=>row.id==='p-456').olcu,'330ML');
assert.equal(data.urunler.find((row)=>row.id==='p-456').gorsel,'/img/products/coca-cola-330.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-457').marka,'Lipton');
assert.equal(data.urunler.find((row)=>row.id==='p-457').ad,'Ice Tea Şeftali');
assert.equal(data.urunler.find((row)=>row.id==='p-457').gorsel,'/img/products/lipton-ice-tea-seftali.webp');
assert.deepEqual(data.urunler.filter((row)=>row.alt==='E3').map((row)=>row.id),[
  'p-456','p-192','p-193','p-450','p-451','p-194','p-195','p-196','p-457',
  'p-198','p-199','p-200','p-205','p-206','p-369','p-388','p-389',
  'p-189','p-190','p-191','p-197','p-201','p-202','p-203','p-204',
]);
assert.equal(data.urunler.find((row)=>row.id==='p-221').gorsel,'/img/products/eti-lifalif-kirmizi.webp');
assert.equal(data.urunler.filter((row)=>row.marka==='Züber').length,5);
assert.equal(data.urunler.find((row)=>row.id==='p-452').ad,'Kakaolu ve Fındıklı Meyve Tatlısı');
assert.equal(data.urunler.find((row)=>row.id==='p-453').ad,'Protein Bar Kakao Parçacıklı');
assert.equal(data.urunler.find((row)=>row.id==='p-454').ad,'Hi Protein Bar Fıstık Ezmeli');
assert.equal(data.urunler.find((row)=>row.id==='p-455').ad,'Antep Fıstıklı ve Kakaolu Meyve Tatlısı');
assert.equal(data.urunler.find((row)=>row.id==='p-458').ad,'Yer Fıstıklı ve Kakaolu Meyve Tatlısı');
assert.equal(data.urunler.find((row)=>row.id==='p-459').urunTuru,'M850L');
assert.equal(data.urunler.find((row)=>row.id==='p-462').urunTuru,'M185');
assert.equal(data.urunler.find((row)=>row.id==='p-463').ad,'Aydınlatmalı Kablosuz Klavye');
assert.equal(data.urunler.find((row)=>row.id==='p-467').olcu,'32GB');
assert.equal(data.urunler.find((row)=>row.id==='p-471').marka,'ttec');
assert.equal(data.urunler.filter((row)=>row.marka==='Duracell').length,5);
assert.equal(data.urunler.filter((row)=>row.marka==='Varta').length,5);
assert.ok(!data.urunler.some((row)=>row.ad==='Çift Sargılı Şeker'));
assert.equal(data.urunler.filter((row)=>row.alt==='D1').length,20);
assert.ok(data.urunler.filter((row)=>row.alt==='D1').every((row)=>row.kategori==='D'));
assert.ok(data.urunler.filter((row)=>row.alt==='D1').every((row)=>row.marka==='Koroplast' || row.marka==='MRP Marin'));
assert.equal(data.urunler.filter((row)=>row.alt==='D1' && row.marka==='Koroplast').length,8);
assert.ok(!data.urunler.some((row)=>row.alt==='D1' && row.marka==='Koroplast' && /Küçük|Battal|Jumbo/.test(row.ad)));
assert.equal(data.urunler.filter((row)=>row.alt==='D1' && row.marka==='MRP Marin').length,12);
assert.ok(data.urunler.filter((row)=>row.marka==='MRP Marin').every((row)=>row.gorsel.startsWith('/img/products/mrp-poset-')));
assert.ok(!data.urunler.some((row)=>row.marka==='MRP Marin' && row.gorsel.includes('koroplast')));
assert.ok(!data.urunler.some((row)=>row.alt==='D1' && /Konteyner|Hantal/.test(row.ad)));
assert.equal(data.urunler.find((row)=>row.id==='p-093').gorsel,'/img/products/mrp-poset-std-mini.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-103').ad,'Özel Ebat Çöp Poşeti');
assert.equal(data.urunler.find((row)=>row.marka==='Ceymop' && row.ad==='Islak Mop').gorsel,'/img/products/ceymop-islak.webp');
assert.ok(data.urunler.filter((row)=>row.marka==='Ceymop' && row.ad==='Nemli Mop').every((row)=>row.gorsel==='/img/products/ceymop-nemli.webp'));
assert.ok(data.urunler.filter((row)=>row.marka==='Ceymop' && row.ad==='Orlon Mop').every((row)=>row.gorsel==='/img/products/ceymop-orlon.webp'));
assert.equal(data.urunler.find((row)=>row.marka==='Parex' && row.ad==='Mikrofiber Cam Bezi').gorsel,'/img/products/parex-cam-bezi.webp');
assert.ok(data.urunler.filter((row)=>row.marka==='Parex' && row.ad==='Mikrofiber Temizlik Bezi').every((row)=>row.gorsel==='/img/products/parex-mikrofiber.webp'));
assert.equal(data.urunler.find((row)=>row.id==='p-070').ad,'Ovma Teli');
assert.equal(data.urunler.find((row)=>row.id==='p-070').gorsel,'/img/products/parex-ovma-teli.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-070').ambalajAdedi,"3'lü");
assert.ok(!data.urunler.some((row)=>row.ad==='Bulaşık Teli'));
assert.equal(data.urunler.find((row)=>row.ad==='Yer Çekme Aparatı' && row.olcu==='55Cm' && row.malzeme==='Plastik').gorsel,'/img/products/yer-cekme-plastik.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Yer Çekme Aparatı' && row.olcu==='75Cm' && row.malzeme==='Plastik').gorsel,'/img/products/yer-cekme-plastik.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Yer Çekme Aparatı' && row.olcu==='55Cm' && row.malzeme==='Metal').gorsel,'/img/products/yer-cekme-metal-55.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Yer Çekme Aparatı' && row.olcu==='75Cm' && row.malzeme==='Metal').gorsel,'/img/products/yer-cekme-metal-75.webp');
assert.ok(data.urunler.filter((row)=>row.ad==='Yer Çekme Aparatı' && row.malzeme==='Metal').every((row)=>row.gorsel.includes('metal')));
assert.ok(data.urunler.filter((row)=>row.ad==='Yer Çekme Aparatı' && row.malzeme==='Plastik').every((row)=>row.gorsel.includes('plastik')));
assert.equal(data.urunler.find((row)=>row.id==='p-075').gorsel,'/img/products/parex-cam-silecegi-35.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-075').ad,'Cam Sileceği');
assert.equal(data.urunler.find((row)=>row.id==='p-075').malzeme,'Plastik');
assert.equal(data.urunler.find((row)=>row.id==='p-075').olcu,'24Cm');
assert.equal(data.urunler.find((row)=>row.id==='p-077').ad,'Cam Sileceği');
assert.equal(data.urunler.find((row)=>row.id==='p-077').malzeme,'Metal');
assert.equal(data.urunler.find((row)=>row.id==='p-077').olcu,'24Cm');
assert.equal(data.urunler.find((row)=>row.id==='p-077').gorsel,'/img/products/parex-cam-silecegi-metal-24.webp');
assert.equal(data.urunler.filter((row)=>row.ad==='Cam Sileceği').length,2);
assert.ok(!data.urunler.some((row)=>row.ad==='Cam Çek-Sil Aparatı'));
assert.equal(data.urunler.filter((row)=>row.ad==='Cam Peluşu').length,2);
assert.ok(data.urunler.filter((row)=>row.ad==='Cam Peluşu').every((row)=>row.marka==='Ceymop' && row.gorsel==='/img/products/ceymop-cam-pelusu.webp'));
assert.equal(data.urunler.find((row)=>row.ad==='Klozet Fırçası' && row.malzeme==='Plastik').marka,'Parex');
assert.equal(data.urunler.find((row)=>row.ad==='Klozet Fırçası' && row.malzeme==='Plastik').gorsel,'/img/products/parex-klozet-fircasi.webp');
assert.ok(!data.urunler.some((row)=>row.ad==='Klozet Fırçası' && row.malzeme==='Metal'));
assert.ok(!data.urunler.some((row)=>row.ad==='Pudrasız Muayene Eldiveni'));
assert.ok(!data.urunler.some((row)=>row.ad==='Temizlik Kovası'));
assert.equal(data.urunler.find((row)=>row.ad==='Oto Fırçası').gorsel,'/img/products/parex-oto-fircasi.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Oto Fırçası').marka,'Parex');
assert.equal(data.urunler.find((row)=>row.ad==='Klozet Fırçası' && row.marka==='Ceymop').gorsel,'/img/products/ceymop-klozet-fircasi.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Nitril Muayene Eldiveni').gorsel,'/img/products/nitril-muayene-eldiveni.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Pudralı Muayene Eldiveni').gorsel,'/img/products/pudrali-muayene-eldiveni.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Çift Kovalı Temizlik Arabası').marka,'Ceymop');
assert.equal(data.urunler.find((row)=>row.ad==='Çift Kovalı Temizlik Arabası').gorsel,'/img/products/ceymop-cift-kovali.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Tek Kovalı Temizlik Seti').gorsel,'/img/products/ceymop-tek-kovali.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Plastik Kat Arabası').gorsel,'/img/products/ceymop-plastik-kat-arabasi.webp');
assert.equal(data.urunler.find((row)=>row.ad==='Krom Kat Arabası').gorsel,'/img/products/ceymop-krom-kat-arabasi.webp');
assert.ok(!data.urunler.some((row)=>row.ad==='Temizlik Seti' && !row.marka));
assert.ok(data.urunler.some((row)=>row.alt==='C4' && row.marka==='Parex' && row.ad==='Extra Power Temizlik Seti'));
assert.equal(data.urunler.find((row)=>row.id==='p-346').gorsel,'/img/products/parex-extra-power-kova.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-349').ad,'Pedallı Otomatik Temizlik Seti');
assert.equal(data.urunler.find((row)=>row.id==='p-349').gorsel,'/img/products/parex-pedalli-otomatik.webp');
assert.equal(data.urunler.filter((row)=>row.alt==='C4').length,15);
assert.equal(data.urunler.find((row)=>row.id==='p-441').ad,'Nemli Mop Aparatı');
assert.equal(data.urunler.find((row)=>row.id==='p-441').marka,'Ceymop');
assert.equal(data.urunler.find((row)=>row.id==='p-441').olcu,'50Cm');
assert.equal(data.urunler.find((row)=>row.id==='p-441').malzeme,'Plastik');
assert.equal(data.urunler.find((row)=>row.id==='p-441').gorsel,'/img/products/ceymop-nemli-mop-aparat-50.webp');
assert.equal(data.urunler.filter((row)=>row.alt==='D2').length,33);
assert.equal(data.urunler.filter((row)=>row.ad==='Faraşlı Süpürge').length,1);
assert.equal(data.urunler.find((row)=>row.ad==='Faraşlı Süpürge').id,'p-086');
assert.equal(data.urunler.find((row)=>row.id==='p-086').malzeme,'');
assert.equal(data.urunler.find((row)=>row.id==='p-431').ad,'Islak Mop Aparatı');
assert.equal(data.urunler.find((row)=>row.id==='p-431').alt,'C4');
assert.equal(data.urunler.find((row)=>row.id==='p-434').urunTuru,'Kulaklı');
assert.equal(data.urunler.find((row)=>row.id==='p-434').alt,'C4');
assert.equal(data.urunler.find((row)=>row.id==='p-436').ad,'Tel Aparatı');
assert.equal(data.urunler.find((row)=>row.id==='p-436').alt,'C4');
assert.ok(['p-431','p-432','p-433','p-434','p-435','p-436'].every((id)=>data.urunler.find((row)=>row.id===id).kategori==='C'));
assert.equal(data.urunler.find((row)=>row.id==='p-105').ad,'Salata Kasesi');
assert.equal(data.urunler.find((row)=>row.id==='p-105').marka,'');
assert.equal(data.urunler.find((row)=>row.id==='p-105').ambalajAdedi,"25'li");
assert.equal(data.urunler.find((row)=>row.id==='p-105').gorsel,'/img/products/salata-kasesi.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-106').ad,'Çorba Kasesi');
assert.equal(data.urunler.find((row)=>row.id==='p-106').marka,'');
assert.equal(data.urunler.find((row)=>row.id==='p-106').kapasite,'16Oz');
assert.equal(data.urunler.find((row)=>row.id==='p-106').ambalajAdedi,"25'li");
assert.equal(data.urunler.find((row)=>row.id==='p-106').urunTuru,'Siyah Kapaklı');
assert.equal(data.urunler.find((row)=>row.id==='p-106').gorsel,'/img/products/siyah-kapakli-corba-kasesi.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-379').ad,'Kraft Çorba Kasesi');
assert.equal(data.urunler.find((row)=>row.id==='p-379').kapasite,'16Oz');
assert.equal(data.urunler.find((row)=>row.id==='p-379').ambalajAdedi,"25'li");
assert.equal(data.urunler.find((row)=>row.id==='p-379').gorsel,'/img/products/kraft-corba-kasesi.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-107').ad,'Plastik Tabak');
assert.equal(data.urunler.find((row)=>row.id==='p-107').marka,'');
assert.equal(data.urunler.find((row)=>row.id==='p-107').gorsel,'/img/products/plastik-tabak.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-113').ad,'Plastik Çatal');
assert.equal(data.urunler.find((row)=>row.id==='p-113').marka,'');
assert.equal(data.urunler.find((row)=>row.id==='p-113').gorsel,'/img/products/plastik-catal.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-114').gorsel,'/img/products/plastik-kasik.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-115').gorsel,'/img/products/plastik-bicak.webp');
assert.ok(!data.urunler.some((row)=>row.marka==='Nur-Nil'));
assert.ok(!data.urunler.some((row)=>row.id==='p-117'));
assert.equal(data.urunler.find((row)=>row.id==='p-445').ad,'Plastik Çatal Bıçak Kaşık Seti');
assert.equal(data.urunler.find((row)=>row.id==='p-446').ad,'Türk Kahvesi Kağıt Bardağı');
assert.equal(data.urunler.find((row)=>row.id==='p-447').ad,'Ekonomik Karton Bardak');
assert.equal(data.urunler.find((row)=>row.id==='p-447').kapasite,'7Oz');
assert.equal(data.urunler.find((row)=>row.id==='p-447').gorsel,'/img/products/ekonomik-karton-bardak-7oz.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-448').ad,'Karton Bardak');
assert.equal(data.urunler.find((row)=>row.id==='p-448').kapasite,'7Oz');
assert.equal(data.urunler.find((row)=>row.id==='p-448').gorsel,'/img/products/karton-bardak-7oz.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-449').ad,'Pipet');
assert.equal(data.urunler.find((row)=>row.id==='p-449').gorsel,'/img/products/pipet.webp');
assert.ok(!data.urunler.find((row)=>row.id==='p-449').marka);
assert.equal(data.urunler.find((row)=>row.id==='p-110').ad,'Köpük Tabak');
assert.equal(data.urunler.find((row)=>row.id==='p-110').gorsel,'/img/products/kopuk-tabak.webp');
assert.ok(!data.urunler.some((row)=>row.ad==='Kağıt Tabak'));
assert.equal(data.urunler.find((row)=>row.id==='p-116').gorsel,'/img/products/kurdan-100.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-442').ad,'Plastik Bardak');
assert.equal(data.urunler.find((row)=>row.id==='p-442').ambalajAdedi,"3000'li");
assert.equal(data.urunler.find((row)=>row.id==='p-443').ad,'Köpük Bardak');
assert.equal(data.urunler.find((row)=>row.id==='p-443').ambalajAdedi,"100'lü");
assert.equal(data.urunler.find((row)=>row.id==='p-444').ad,'Karton Kahve Bardağı');
assert.ok(!data.urunler.some((row)=>row.ad==='Karton Tabak'));
assert.equal(data.urunler.filter((row)=>row.ad==='Plastik Tabak').length,1);
assert.equal(data.urunler.find((row)=>row.id==='p-118').ad,'Aşçı Kepi');
assert.equal(data.urunler.find((row)=>row.id==='p-118').gorsel,'/img/products/asci-kepi.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-119').marka,'Dolphin');
assert.equal(data.urunler.find((row)=>row.id==='p-119').gorsel,'/img/products/seffaf-eldiven.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-120').marka,'Dolphin');
assert.equal(data.urunler.find((row)=>row.id==='p-120').gorsel,'/img/products/tela-bone.webp');
assert.ok(!data.urunler.some((row)=>row.ad==='Aşçı Kepçesi'));
assert.equal(data.urunler.find((row)=>row.id==='p-123').marka,'Parex');
assert.equal(data.urunler.find((row)=>row.id==='p-123').ambalajAdedi,"40'lı");
assert.equal(data.urunler.find((row)=>row.id==='p-123').olcu,'20 × 30 Cm');
assert.equal(data.urunler.find((row)=>row.id==='p-123').gorsel,'/img/products/parex-buz-kucuk.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-124').marka,'Parex');
assert.equal(data.urunler.find((row)=>row.id==='p-124').ambalajAdedi,"20'li");
assert.equal(data.urunler.find((row)=>row.id==='p-124').olcu,'24 × 38 Cm');
assert.equal(data.urunler.find((row)=>row.id==='p-124').gorsel,'/img/products/parex-buz-orta.webp');
assert.ok(!data.urunler.some((row)=>row.ad==='Büyük Boy Buzdolabı Poşeti'));
assert.equal(data.urunler.filter((row)=>row.ad==='Buzdolabı Poşeti' || row.ad.endsWith('Buzdolabı Poşeti')).length,2);
assert.equal(data.urunler.find((row)=>row.id==='p-122').marka,'Parex');
assert.equal(data.urunler.find((row)=>row.id==='p-122').olcu,'8M');
assert.equal(data.urunler.find((row)=>row.id==='p-122').gorsel,'/img/products/parex-folyo-8.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-365').marka,'Parex');
assert.equal(data.urunler.find((row)=>row.id==='p-365').olcu,'15M');
assert.equal(data.urunler.find((row)=>row.id==='p-365').gorsel,'/img/products/parex-folyo-15.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-126').marka,'Parex');
assert.equal(data.urunler.find((row)=>row.id==='p-126').olcu,'15M');
assert.equal(data.urunler.find((row)=>row.id==='p-126').gorsel,'/img/products/parex-strec-15.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-366').marka,'Parex');
assert.equal(data.urunler.find((row)=>row.id==='p-366').olcu,'33M');
assert.equal(data.urunler.find((row)=>row.id==='p-366').gorsel,'/img/products/parex-strec-33.webp');
assert.ok(data.urunler.filter((row)=>row.ad==='Alüminyum Folyo').every((row)=>row.marka==='Parex' && !row.gorsel.includes('koroplast')));
assert.ok(data.urunler.filter((row)=>row.ad==='Streç Film').every((row)=>row.marka==='Parex' && !row.gorsel.includes('koroplast')));
assert.equal(data.urunler.filter((row)=>row.alt==='D3').length,29);
assert.equal(data.urunler.filter((row)=>row.ad==='Orta Boy Çöp Poşeti').length,7);
assert.match(readFileSync(new URL('../public/urunler.html',import.meta.url),'utf8'),/id="kat-daireler"/);
assert.match(readFileSync(new URL('../public/catalog-ui.js',import.meta.url),'utf8'),/kat-daireler/);
assert.match(readFileSync(new URL('../public/catalog-ui.js',import.meta.url),'utf8'),/product-detail/);
assert.match(readFileSync(new URL('../public/catalog-ui.js',import.meta.url),'utf8'),/tokens\.includes\(needle\)/);
assert.match(readFileSync(new URL('../public/catalog-ui.js',import.meta.url),'utf8'),/photoZoom/);
assert.equal(data.urunler.find((row)=>row.id==='p-041').gorsel,'/img/products/yumos-pro-yasemin-5lt.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-042').gorsel,'/img/products/vernel-hassas-5lt.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-021').gorsel,'/img/products/ozopak-yuzey-5kg.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-027').gorsel,'/img/products/ozopak-bulasik-5kg.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-043').ad,'Çamaşır Suyu');
assert.equal(data.urunler.find((row)=>row.id==='p-043').olcu,'750ML');
assert.equal(data.urunler.find((row)=>row.id==='p-043').gorselTuru,'urun');
assert.equal(data.urunler.find((row)=>row.id==='p-044').ad,'Domestos Çamaşır Suyu');
assert.equal(data.urunler.find((row)=>row.id==='p-044').olcu,'3,2Lt');
assert.equal(data.urunler.find((row)=>row.id==='p-044').gorsel,'/img/products/domestos-cam-32.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-044').gorselTuru,'urun');
assert.equal(data.urunler.find((row)=>row.id==='p-047').gorsel,'/img/products/pril-ultra-guc-4kg.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-048').gorsel,'/img/products/bingo-fresh-masal-25.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-023').ad,'Sıvı El Yıkama Maddesi');
assert.equal(data.urunler.find((row)=>row.id==='p-023').gorsel,'/img/products/ozopak-el-yikama.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-024').gorsel,'/img/products/ozopak-el-yikama.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-025').gorsel,'/img/products/ozopak-camasir-suyu-5kg.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-030').gorsel,'/img/products/ozopak-makine-parlatici.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-427').ad,'Ultra Deterjan Katkılı Çamaşır Suyu');
assert.equal(data.urunler.find((row)=>row.id==='p-427').olcu,'5Kg');
assert.equal(data.urunler.find((row)=>row.id==='p-427').gorsel,'/img/products/ozopak-ultra-camasir-suyu.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-428').olcu,'20Kg');
assert.equal(data.urunler.find((row)=>row.id==='p-428').gorsel,'/img/products/ozopak-ultra-camasir-suyu.webp');
assert.equal(data.urunler.filter((row)=>row.alt==='B1' && row.marka==='Ozopak').length,22);
assert.equal(data.urunler.find((row)=>row.id==='p-053').gorsel,'/img/products/asperox-mavi-guc.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-054').gorsel,'/img/products/cif-krem-limon.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-055').gorsel,'/img/products/cif-krem-limon-750.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-058').gorsel,'/img/products/porcoz-jel-lavabo.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-059').marka,'Bref');
assert.equal(data.urunler.find((row)=>row.id==='p-059').ad,'Power Aktiv');
assert.equal(data.urunler.find((row)=>row.id==='p-059').urunTuru,'Okyanus');
assert.equal(data.urunler.find((row)=>row.id==='p-059').gorsel,'/img/products/bref-power-aktiv.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-129').ad,'Masa Üstü Z Peçete Aparatı');
assert.equal(data.urunler.find((row)=>row.id==='p-133').gorsel,'/img/products/palex-ev-tipi-metal.webp');
assert.equal(data.urunler.find((row)=>row.id==='p-133').malzeme,'Plastik');
assert.equal(data.urunler.find((row)=>row.id==='p-135').ad,'Mini İçten Çekmeli Tuvalet Kağıdı Aparatı');
assert.equal(data.urunler.find((row)=>row.id==='p-135').gorsel,'/img/products/palex-mini-icten-tuvalet.webp');
assert.equal(data.urunler.find((row)=>row.marka==='Yumoş' && row.urunTuru==='Sakura').gorselTuru,'urun');
assert.ok(!JSON.stringify(data).includes('santimetre'));
assert.ok(!JSON.stringify(data).includes('mililitre'));
assert.ok(!JSON.stringify(data).includes('kilogram'));
assert.ok(!JSON.stringify(data).includes('Çam Kokulu'));
for(const row of data.urunler){
  assert.ok(row.ad);
  assert.ok((ALTLAR_IDS[row.kategori]||[]).includes(row.alt), row.ad + ' ' + row.alt);
  assert.match(row.gorsel,/^\/img\/[a-z0-9/-]+\.webp$/);
  assert.ok(existsSync(new URL('../public'+row.gorsel,import.meta.url)),row.gorsel);
  assert.ok(['kategori','urun'].includes(row.gorselTuru), row.id + ' ' + row.gorselTuru);
  const expectedPhoto = {
    'p-001': '/img/products/espiga-fotoselli-havlu.webp',
    'p-002': '/img/products/espiga-icten-cekmeli-havlu.webp',
    'p-003': '/img/products/espiga-z-katli-havlu-100.webp',
    'p-004': '/img/products/espiga-z-katli-havlu-200.webp',
    'p-005': '/img/products/belinno-ev-tipi-rulo-6.webp',
    'p-006': '/img/products/solo-dev-rulo-havlu.webp',
    'p-007': '/img/products/selpak-dev-rulo-havlu.webp',
    'p-252': '/img/products/pensan-tukenmez-siyah.webp',
    'p-267': '/img/products/faber-min-07-2b.webp',
    'p-284': '/img/products/mas-zimba-no10-siyah.webp',
    'p-292': '/img/products/mas-istampa-8x9.webp',
    'p-294': '/img/products/noki-klasor-genis-mavi.webp',
    'p-307': '/img/products/esselte-sikistirmali-siyah.webp',
    'p-308': '/img/products/noki-sekreter-kapakli.webp',
  };
  if (expectedPhoto[row.id]) {
    assert.equal(row.gorselTuru,'urun');
    assert.equal(row.gorsel, expectedPhoto[row.id]);
  }
  assert.equal(row.aktif,true);
}

async function checkSubmission(ok) {
  let submit, sent, reset=false, cleared=false;
  const elements=Object.fromEntries(Object.entries({firma:'TEST',yetkili:'',tel:'00000000000',grup:'',ilce:'',not:''}).map(([key,value])=>[key,{value}]));
  const button={disabled:false}; const msg={};
  const form={elements,addEventListener:(type,handler)=>{submit=handler;},querySelector:()=>button,reset:()=>{reset=true;}};
  const c=vm.createContext({URLSearchParams,location:{search:''},
    document:{querySelectorAll:()=>[],querySelector:()=>null,getElementById:id=>id==='siparis-form'?form:id==='msg'?msg:null},
    window:{FerraInterest:{summary:()=> 'Temizlik: El Sabunları',clear:()=>{cleared=true;}}},
    fetch:async (_url,options)=>{sent=JSON.parse(options.body);return {ok,headers:{get:()=> 'application/json'},json:async()=>ok?{ok:true}:{error:'test failure'}};},
  });
  vm.runInContext(script,c);
  await submit({preventDefault(){}});
  assert.equal(sent.not,'Temizlik: El Sabunları');
  assert.equal(reset,ok);
  assert.equal(cleared,ok,'Selection must clear only after confirmed success');
  assert.equal(button.disabled,false);
}
await checkSubmission(true);
await checkSubmission(false);
console.log(`PASS: ${data.urunler.length} catalogue rows classified; form includes selections and preserves them on failure.`);

assert.equal(vm.runInContext('aramaMetni("KAĞIT Çay ŞEKER ıslak")',context),'kagit cay seker islak');
