import assert from 'node:assert/strict';
import worker from '../src/worker.js';
import {notifyQuote} from '../src/quote-notify.js';
const stored=new Map(), points=[], keys=[];
const env={SESSION_SECRET:'isolated-test-only',KV:{put:async(k,v)=>stored.set(k,v)},QUOTE_RATE_LIMITER:{limit:async({key})=>{keys.push(key);return {success:false};}},METRICS:{writeDataPoint:p=>points.push(p)}};
const request=body=>new Request('https://ferrapro.com/api/teklif',{method:'POST',headers:{origin:'https://ferrapro.com','cf-connecting-ip':'192.0.2.1'},body:JSON.stringify(body)});
const quote={firma:'TEST ONLY',tel:'00000000000'};
let res=await worker.fetch(request(quote),env);
assert.equal(res.status,429);assert.equal(res.headers.get('retry-after'),'60');assert.equal(stored.size,0);
assert.match(keys[0],/^[a-f0-9]{64}$/);assert.ok(!keys[0].includes('192.0.2.1'));
env.QUOTE_RATE_LIMITER.limit=async()=>{throw Error('provider secret detail');};
res=await worker.fetch(request(quote),env);assert.equal(res.status,503);assert.doesNotMatch(await res.text(),/secret detail/);
env.QUOTE_RATE_LIMITER.limit=async()=>({success:true});
res=await worker.fetch(request({...quote,not:'x'.repeat(13000)}),env);assert.equal(res.status,413);assert.equal(stored.size,0);
const sent=[];env.QUOTE_NOTIFY_FROM='info@ferrapro.com';env.QUOTE_NOTIFY_TO='first@example.test,second@example.test';
env.QUOTE_EMAIL={send:async message=>{sent.push(message);if(message.to.startsWith('second'))throw Error('mail failure');}};
res=await worker.fetch(request(quote),env);assert.equal(res.status,200);
assert.equal([...stored.keys()].filter(k=>k.startsWith('vitrin-quote:')).length,1);
assert.equal(sent.length,2);assert.ok(sent.every(m=>!m.text.includes(quote.tel)&&!m.text.includes(quote.firma)));
assert.equal(JSON.parse([...stored.entries()].find(([k])=>k.startsWith('vitrin-notification:'))[1]).status,'partial');
assert.equal(points.at(-1).blobs[0],'quote_saved');
env.QUOTE_EMAIL.send=()=>{throw Error('synchronous failure');};
assert.equal((await notifyQuote(env,{id:'test',created_at:'2026-10-05'})).status,'failed');
const metric=(data,headers={})=>worker.fetch(new Request('https://ferrapro.com/api/olcum',{method:'POST',headers:{origin:'https://ferrapro.com',...headers},body:JSON.stringify(data)}),env);
assert.equal((await metric({event:'page_view',page:'home'})).status,204);
const count=points.length;
assert.equal((await metric({event:'page_view',page:'home',tel:'secret'})).status,400);
assert.equal((await metric({event:'quote_saved',page:'request'})).status,400,'Client cannot forge saved quote event');
assert.equal((await metric({event:'page_view',page:'home'},{origin:'https://unrelated.example'})).status,403);
assert.equal((await metric({event:'page_view',page:'home'},{dnt:'1'})).status,204);
assert.equal(points.length,count);
console.log('PASS: rate rejection, bounded body, isolated recipients, delivery failures preserve quote, metric allowlists and privacy headers.');
