import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import vm from 'node:vm';

const script=readFileSync(new URL('../public/site.js',import.meta.url),'utf8');
const context=vm.createContext({
  document:{querySelectorAll:()=>[],querySelector:()=>null,getElementById:()=>null},
});
vm.runInContext(script,context);
const classify=(group,text,alt)=>vm.runInContext(`altBul(${JSON.stringify(group)},${JSON.stringify(text)},${JSON.stringify(alt)}).id`,context);
assert.equal(classify('Temizlik','Doğal Güç Mop Beyaz 1×50'),'arac');
assert.equal(classify('Temizlik','Sıvı el sabunu 5 L'),'sabun');
assert.equal(classify('Temizlik','Sıvı el sabunu 1 L'),'sabun');
assert.equal(classify('Temizlik','Köpük el sabunu 1 L'),'sabun');
assert.equal(classify('Temizlik','Sıvı sabun dispenseri'),'sabun');
assert.equal(classify('Temizlik','Kıvamlı çamaşır suyu 20 kg'),'camasir-suyu');
assert.equal(classify('Temizlik','Çamaşır Deterjanı 10 kg'),'camasir');
assert.equal(classify('Mutfak','Çay 1 kg'),'kahve');
assert.equal(classify('Mutfak','Ice Tea Şeftali 330 ml'),'icecek');
const data=JSON.parse(readFileSync(new URL('../public/katalog.json',import.meta.url),'utf8'));
for(const row of data.urunler) assert.notEqual(classify(row.kategori,row.satir,row.alt),'diger',row.satir);
for(const row of data.urunler){
  assert.match(row.gorsel,/^\/img\/[a-z0-9/-]+\.webp$/);
  assert.ok(existsSync(new URL('../public'+row.gorsel,import.meta.url)),row.gorsel);
  assert.ok(['temsili','kategori'].includes(row.gorselTuru));
}
for(const [group,min] of Object.entries({Hijyen:80,Temizlik:90,Mutfak:90,Ambalaj:45,PC:50,Sağlık:45}))assert.ok(data.urunler.filter(r=>r.kategori===group).length>=min,group);

const stationery=data.urunler.filter(r=>r.kategori==='Kırtasiye');
assert.ok(stationery.length >= 50);
assert.equal(new Set(stationery.map(r=>r.satir)).size,stationery.length);
assert.equal(new Set(stationery.map(r=>r.alt)).size,11);
assert.equal(classify('Hijyen','Islak havlu 90’lı','islak'),'islak');
assert.equal(classify('Hijyen','Yüzey temizlik havlusu','islak'),'islak');
assert.equal(vm.runInContext('MARKA_TERCIHLERI.islak.join(",")',context),'Espiga,Polente,Sleepy,Selpak,Freshmaker,Papilion,Deep Fresh,Komili');
assert.equal(vm.runInContext(`markaTercihSatir(${JSON.stringify('Islak havlu 90’lı')},${JSON.stringify('Espiga')})`,context),'Islak havlu 90’lı · Marka tercihi: Espiga');
assert.equal(vm.runInContext(`markaTercihSatir(${JSON.stringify('Islak havlu 90’lı')},${JSON.stringify('Fark etmez')})`,context),'Islak havlu 90’lı · Marka tercihi: fark etmez');
assert.equal(classify('Hijyen','Peçete 100’lü','pecete'),'pecete');
assert.equal(classify('Hijyen','Z peçete','pecete'),'pecete');
assert.equal(classify('Hijyen','Renkli peçete','pecete'),'pecete');
assert.equal(classify('Hijyen','Z kat havlu dispenseri','dispenser'),'dispenser');
assert.equal(classify('Hijyen','Masaüstü peçete dispenseri','dispenser'),'dispenser');
assert.equal(classify('Hijyen','Rulo havlu 6’lı','havlu'),'havlu');
assert.equal(classify('Hijyen','Dev rulo havlu','havlu'),'havlu');
assert.equal(vm.runInContext('MARKA_TERCIHLERI.havlu.join(",")',context),'Solo,Selpak,Papia,Familia,Focus,Forest,Rulopak');
assert.ok(!vm.runInContext('ALTLAR.Hijyen.map(x=>x.id).join(",")',context).split(',').includes('mendil'));
assert.equal(data.urunler.filter(r=>r.alt==='mendil').length,0);
for (const row of data.urunler.filter(r=>/çöp poşet/i.test(r.satir))) {
  if (/mavi/i.test(row.satir)) assert.match(row.gorsel,/copblue\.webp$/);
  else if (/şeffaf/i.test(row.satir)) assert.match(row.gorsel,/copclear\.webp$/);
  else if (/siyah/i.test(row.satir)) assert.match(row.gorsel,/copblack\.webp$/);
}
assert.ok(data.urunler.some(r=>r.satir.startsWith('Sıvı El Sabunu 5 L')&&r.gorsel.endsWith('soap5l.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Sıvı El Sabunu 1 L')&&r.gorsel.endsWith('soap.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Köpük El Sabunu')&&r.gorsel.endsWith('foamsoap.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Sıvı Sabun Dispenseri'&&r.gorsel.endsWith('soapdisp.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Köpük Sabun Dispenseri'&&r.gorsel.endsWith('foamdisp.webp')));
assert.equal(data.urunler.filter(r=>r.satir==='Sıvı el sabunu').length,0);
assert.equal(vm.runInContext('urunAdiYazi("Sıvı el sabunu 1 L · 1 litre pompalı şişe")',context),'Sıvı El Sabunu 1 L · 1 Litre Pompalı Şişe');
for (const row of data.urunler) assert.equal(row.satir, vm.runInContext(`urunAdiYazi(${JSON.stringify(row.satir)})`,context), row.satir);
const bleach=data.urunler.filter(r=>/çamaşır suyu/i.test(r.satir));
assert.equal(bleach.length,5);
assert.ok(bleach.every(r=>classify(r.kategori,r.satir,r.alt)==='camasir-suyu'));
assert.ok(bleach.every(r=>!r.gorsel.endsWith('cleaner.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Sıvı Çamaşır Suyu 1 L')&&r.gorsel.endsWith('bleach1l.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Sıvı Çamaşır Suyu 5 L')&&r.gorsel.endsWith('bleach5l.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Sıvı Çamaşır Suyu 20 L')&&r.gorsel.endsWith('bleach20l.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Kıvamlı Çamaşır Suyu 4 kg')&&r.gorsel.endsWith('thickbleach4.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Kıvamlı Çamaşır Suyu 20 kg')&&r.gorsel.endsWith('thickbleach20.webp')));
const wash=data.urunler.filter(r=>/çamaşır/i.test(r.satir)&&!/çamaşır suyu/i.test(r.satir));
assert.equal(wash.length,6);
assert.ok(wash.every(r=>classify(r.kategori,r.satir,r.alt)==='camasir'));
assert.ok(wash.every(r=>!r.gorsel.endsWith('detergent.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Toz Çamaşır Deterjanı 10 kg')&&r.gorsel.endsWith('washpowder.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Sıvı Çamaşır Deterjanı 3 L')&&r.gorsel.endsWith('washliq3.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Sıvı Çamaşır Deterjanı 5 L')&&r.gorsel.endsWith('washliq5.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Kapsül Çamaşır Deterjanı')&&r.gorsel.endsWith('washcaps.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Çamaşır Yumuşatıcısı 5 L')&&r.gorsel.endsWith('softener.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Çamaşır Leke Çıkarıcı')&&r.gorsel.endsWith('stainrem.webp')));
assert.equal(data.urunler.filter(r=>r.satir.startsWith('Toz Deterjan 10 kg')).length,0);
const yuzey=data.urunler.filter(r=>r.kategori==='Temizlik'&&(r.alt==='yuzey'||/yüzey/i.test(r.satir)));
assert.equal(new Set(yuzey.map(r=>r.gorsel)).size,yuzey.length);
assert.ok(data.urunler.some(r=>r.satir==='Cam Temizleyici'&&r.gorsel.endsWith('cleaner.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Arap Sabunu'&&r.gorsel.endsWith('arapsoap.webp')));
const kirec=data.urunler.filter(r=>r.alt==='kirec'||/^Kireç Çözücü$|^Pas Sökücü$|^Banyo Temizleyici$|^Klozet Temizleyici$/.test(r.satir));
assert.equal(kirec.length,4);
assert.equal(new Set(kirec.map(r=>r.gorsel)).size,4);
assert.ok(kirec.every(r=>!r.gorsel.endsWith('detergent.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Kireç Çözücü'&&r.gorsel.endsWith('cifkirec.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Pas Sökücü'&&r.gorsel.endsWith('cifpas.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Banyo Temizleyici'&&r.gorsel.endsWith('cifbanyo.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Klozet Temizleyici'&&r.gorsel.endsWith('cifklozet.webp')));
const koku=data.urunler.filter(r=>r.alt==='koku'||/oda parfüm/i.test(r.satir));
assert.equal(koku.length,4);
assert.equal(new Set(koku.map(r=>r.gorsel)).size,4);
assert.ok(data.urunler.some(r=>r.satir==='Oda Kokusu Spreyi'&&r.gorsel.endsWith('odaspray.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Otomatik Koku Makinesi'&&r.gorsel.endsWith('airfreshener.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Koku Makinesi Yedeği'&&r.gorsel.endsWith('kokuyedek.webp')));
assert.ok(data.urunler.some(r=>r.satir.startsWith('Oda Parfümü 500 ml')&&r.gorsel.endsWith('odaparfum.webp')));
assert.ok(data.urunler.filter(r=>/sarı güç/i.test(r.satir)).every(r=>r.gorsel.endsWith('sariguc.webp')));
assert.ok(data.urunler.filter(r=>/mavi güç/i.test(r.satir)).every(r=>r.gorsel.endsWith('maviguc.webp')));
assert.equal(data.urunler.filter(r=>r.satir.startsWith('Bulaşık 4 kg')).length,0);
const dish=data.urunler.filter(r=>r.kategori==='Temizlik'&&(r.alt==='bulasik-temizlik'||/bulaşık/.test(r.satir)));
assert.equal(dish.length,5);
assert.equal(new Set(dish.map(r=>r.gorsel)).size,5);
assert.ok(data.urunler.some(r=>r.satir==='Elde Bulaşık Deterjanı'&&r.gorsel.endsWith('dishhand.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Makine Bulaşık Deterjanı'&&r.gorsel.endsWith('dishmachine.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Bulaşık Makinesi Parlatıcısı'&&r.gorsel.endsWith('dishrinse.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Bulaşık Makinesi Tuzu'&&r.gorsel.endsWith('dishsalt.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Yağ Çözücü'&&r.gorsel.endsWith('degreaser.webp')));
const bezmop=data.urunler.filter(r=>r.kategori==='Temizlik'&&classify(r.kategori,r.satir,r.alt)==='arac');
assert.equal(bezmop.length,11);
assert.equal(new Set(bezmop.map(r=>r.gorsel)).size,11);
assert.ok(data.urunler.some(r=>r.satir==='Mikrofiber Temizlik Bezi'&&r.gorsel.endsWith('cloth.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Cam Bezi'&&r.gorsel.endsWith('camcloth.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Toz Bezi'&&r.gorsel.endsWith('dustcloth.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Islak Mop'&&r.gorsel.endsWith('wetmop.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Nemli Mop'&&r.gorsel.endsWith('dampmop.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Mop Yedeği'&&r.gorsel.endsWith('moprefill.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Mop Aparatı'&&r.gorsel.endsWith('mopframe.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Mop Sapı'&&r.gorsel.endsWith('mophandle.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Temizlik Kovası'&&r.alt==='arac'&&r.gorsel.endsWith('mopbucket.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Presli Temizlik Kovası'&&r.alt==='arac'&&r.gorsel.endsWith('wringerbucket.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Tuvalet Fırçası'&&r.alt==='arac'&&r.gorsel.endsWith('toiletbrush.webp')));
assert.equal(data.urunler.filter(r=>r.satir.startsWith('Krom Tuvalet Fırçası')||r.satir.startsWith('Doğal Güç Mop')).length,0);
const ekip=data.urunler.filter(r=>r.alt==='ekipman');
assert.equal(ekip.length,5);
assert.equal(new Set(ekip.map(r=>r.gorsel)).size,5);
assert.ok(ekip.every(r=>!/\/(brush|mop|bucket)\.webp$/.test(r.gorsel)));
assert.ok(data.urunler.some(r=>r.satir==='Faraşlı Süpürge'&&r.gorsel.endsWith('dustpan.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Yer Fırçası'&&r.gorsel.endsWith('floorbrush.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Cam Çekçeği'&&r.gorsel.endsWith('windowsqueegee.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Yer Çekçeği'&&r.gorsel.endsWith('floorsqueegee.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Temizlik Arabası'&&r.gorsel.endsWith('janitorcart.webp')));
const atik=data.urunler.filter(r=>r.alt==='atik-yonetimi');
assert.equal(atik.length,3);
assert.equal(new Set(atik.map(r=>r.gorsel)).size,3);
assert.equal(data.urunler.filter(r=>r.satir==='Çöp Kovası Kapağı').length,0);
assert.ok(data.urunler.some(r=>r.satir==='Pedallı Çöp Kovası'&&r.gorsel.endsWith('bin.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Ofis Çöp Sepeti'&&r.gorsel.endsWith('officebasket.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Geri Dönüşüm Kutusu'&&r.gorsel.endsWith('recyclebin.webp')));
const tibbi=data.urunler.filter(r=>r.kategori==='Sağlık'&&r.alt==='atik');
assert.ok(tibbi.some(r=>r.satir==='Tıbbi Atık Kovası'));
assert.ok(tibbi.some(r=>r.satir==='Tıbbi Atık Poşeti'));
assert.ok(tibbi.some(r=>r.satir==='Kesici Delici Atık Kutusu'));
assert.equal(data.urunler.filter(r=>r.satir.startsWith('Tıbbi Atık Kovası 5 L')).length,0);
assert.ok(data.urunler.some(r=>r.satir==='Mantar Pano'&&r.gorsel.endsWith('corkboard.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Askılı Dosya'&&r.gorsel.endsWith('hangingfile.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Düğme Pil'&&r.gorsel.endsWith('buttonbatt.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Hava Kabarcıklı Zarf'&&r.gorsel.endsWith('bubblemailer.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Zımba Sökücü'&&r.gorsel.endsWith('stapleremover.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Cilt Spirali'&&r.gorsel.endsWith('bindcoil.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Sayfa Işaretleyici'&&r.gorsel.endsWith('pageflags.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Dosya Ayracı'&&r.gorsel.endsWith('filetabs.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Sunum Dosyası'&&r.gorsel.endsWith('displaybook.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Ataş'&&r.gorsel.endsWith('paperclips.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Evrak Mandalı'&&r.gorsel.endsWith('binderclips.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Kalemlik'&&r.gorsel.endsWith('pencup.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Evrak Rafı'&&r.gorsel.endsWith('papertray.webp')));
const kagit=data.urunler.filter(r=>r.kategori==='Kırtasiye'&&r.alt==='a4');
assert.equal(kagit.length,9);
assert.equal(new Set(kagit.map(r=>r.gorsel)).size,9);
assert.ok(data.urunler.some(r=>r.satir==='A3 Fotokopi Kâğıdı'&&r.gorsel.endsWith('a3ream.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Gramajlı Baskı Kâğıdı'&&r.gorsel.endsWith('gramaj.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Plotter Kâğıdı'&&r.gorsel.endsWith('plotterrolls.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Sürekli Form Kâğıdı'&&r.gorsel.endsWith('contform.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Karbon Kâğıdı'&&r.gorsel.endsWith('carbonpaper.webp')));
assert.ok(data.urunler.some(r=>r.satir==='A4 Fotokopi Kâğıdı'&&r.gorsel.endsWith('a4.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Termal POS Rulosu'&&r.gorsel.endsWith('paperroll.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Jel Kalem'&&r.gorsel.endsWith('gelpen.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Roller Kalem'&&r.gorsel.endsWith('rollerpen.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Beyaz Tahta Kalemi'&&r.gorsel.endsWith('boardmarker.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Asetat Kalemi'&&r.gorsel.endsWith('acetatepen.webp')));
assert.ok(data.urunler.some(r=>r.satir==='İmza Kalemi'&&r.gorsel.endsWith('signpen.webp')));
assert.equal(data.urunler.filter(r=>r.satir==='Karton Klasör').length,0);
const klasor=data.urunler.filter(r=>r.kategori==='Kırtasiye'&&r.alt==='klasor');
assert.equal(klasor.length,5);
assert.ok(data.urunler.some(r=>r.satir==='Geniş Klasör'&&r.gorsel.endsWith('widebinder.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Dar Klasör'&&r.gorsel.endsWith('narrowbinder.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Halkalı Klasör'&&r.gorsel.endsWith('ringbinder.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Arşiv Kutusu'&&r.gorsel.endsWith('archivebox.webp')));
assert.equal(data.urunler.filter(r=>r.satir==='Telli Dosya').length,0);
assert.equal(data.urunler.filter(r=>r.satir==='Sıkıştırmalı Dosya').length,0);
assert.equal(data.urunler.filter(r=>r.satir==='Proje Dosyası').length,0);
const dosya=data.urunler.filter(r=>r.kategori==='Kırtasiye'&&r.alt==='dosya');
assert.equal(dosya.length,8);
assert.equal(data.urunler.filter(r=>r.satir==='Tarihsiz Ajanda'||r.satir==='Tarihli Ajanda'||r.satir==='Fihrist').length,0);
const defter=data.urunler.filter(r=>r.kategori==='Kırtasiye'&&r.alt==='not');
assert.equal(defter.length,9);
assert.ok(data.urunler.some(r=>r.satir==='Spiralli Defter'&&r.gorsel.endsWith('spiralnb.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Ajandalar'&&r.gorsel.endsWith('planner.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Bloknot'&&r.gorsel.endsWith('notepad.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Yapışkanlı Not Kâğıdı'&&r.gorsel.endsWith('stickynotes.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Ticari Defter'&&r.gorsel.endsWith('ledger.webp')));
assert.equal(data.urunler.filter(r=>r.satir==='Arşiv Tipi Zımba Makinesi').length,0);
const zimba=data.urunler.filter(r=>r.kategori==='Kırtasiye'&&r.alt==='zimba');
assert.equal(zimba.length,9);
assert.ok(data.urunler.some(r=>r.satir==='Istampa'&&r.gorsel.endsWith('stamppad.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Maket Bıçağı Yedeği'&&r.gorsel.endsWith('cutterblades.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Maket Bıçağı'&&r.gorsel.endsWith('cutter.webp')));
assert.ok(data.urunler.some(r=>r.kategori==='Kırtasiye'&&r.satir==='Şeffaf Ofis Bandı'&&r.gorsel.endsWith('cleartape.webp')));
assert.ok(data.urunler.some(r=>r.kategori==='Kırtasiye'&&r.satir==='Çift Taraflı Bant'&&r.gorsel.endsWith('doublesided.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Sıvı Yapıştırıcı'&&r.gorsel.endsWith('liquidglue.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Sıvı Düzeltici'&&r.gorsel.endsWith('liquidcorrector.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Stick Yapıştırıcı'&&r.gorsel.endsWith('glue.webp')));
assert.ok(data.urunler.some(r=>r.satir==='Şerit Düzeltici'&&r.gorsel.endsWith('correction.webp')));



// Exercise the real public form handler without network or private customer data.
async function checkSubmission(ok) {
  let submit, sent, reset=false, cleared=false;
  const elements=Object.fromEntries(Object.entries({firma:'TEST',yetkili:'',tel:'00000000000',grup:'',ilce:'',not:''}).map(([key,value])=>[key,{value}]));
  const button={disabled:false}; const msg={};
  const form={elements,addEventListener:(type,handler)=>{submit=handler;},querySelector:()=>button,reset:()=>{reset=true;}};
  const c=vm.createContext({URLSearchParams,location:{search:''},
    document:{querySelectorAll:()=>[],querySelector:()=>null,getElementById:id=>id==='siparis-form'?form:id==='msg'?msg:null},
    window:{FerraInterest:{summary:()=> 'Temizlik: El Sabunları',clear:()=>{cleared=true;}}},
    fetch:async (_url,options)=>{sent=JSON.parse(options.body);return {ok,headers:{get:()=> 'application/json'},json:async()=>ok?{ok:true}:{error:'test failure'}};},
  });
  vm.runInContext(script,c);
  await submit({preventDefault(){}});
  assert.equal(sent.not,'Temizlik: El Sabunları');
  assert.equal(reset,ok);
  assert.equal(cleared,ok,'Selection must clear only after confirmed success');
  assert.equal(button.disabled,false);
}
await checkSubmission(true);
await checkSubmission(false);
console.log(`PASS: ${data.urunler.length} catalogue rows classified; cleaning/tea regressions; form includes selections and preserves them on failure.`);
