import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import worker from '../src/worker.js';
import {ManagementSessions} from '../src/management-sessions.js';
import {managementTestEnv} from './management-test-env.mjs';
const env={...managementTestEnv(),YONETIM_PASSWORD:randomUUID(),SESSION_SECRET:randomUUID(),ASSETS:{fetch:async()=>new Response('private')}};
const send=(path,options={})=>worker.fetch(new Request('https://ferrapro.com/yonetim/'+path,options),env);
const login=()=>send('giris',{method:'POST',body:new URLSearchParams({password:env.YONETIM_PASSWORD})});
const a=await login(),b=await login();
assert.equal(a.status,302);assert.equal(b.status,302);
assert.equal(a.headers.get('cache-control'),'no-store');
const cookie=a.headers.get('set-cookie').split(';')[0],other=b.headers.get('set-cookie').split(';')[0];
assert.notEqual(cookie,other,'Each login receives an independent random session');
assert.match(a.headers.get('set-cookie'),/Max-Age=28800; HttpOnly; SameSite=Lax; Secure/);
assert.equal((await send('catalog.json',{headers:{cookie}})).status,200);
assert.equal((await send('cikis',{headers:{cookie}})).status,302);
assert.equal((await send('catalog.json',{headers:{cookie}})).status,401,'Copied cookie revoked after logout');
assert.equal((await send('catalog.json',{headers:{cookie:other}})).status,200,'Other session remains valid');
env.YONETIM_PASSWORD=randomUUID();
assert.equal((await send('catalog.json',{headers:{cookie:other}})).status,401,'Credential rotation invalidates prior sessions');
assert.equal((await send('catalog.json',{headers:{cookie:'fp_yonetim=%ZZ'}})).status,401);
assert.equal((await send('giris',{method:'POST',headers:{origin:'https://unrelated.example'},body:'password=test'})).status,403);
assert.equal((await send('giris',{method:'POST',body:'x'.repeat(5000)})).status,413);
const binding=env.MANAGEMENT_SESSIONS;
env.MANAGEMENT_SESSIONS={idFromName:n=>n,get:()=>({fetch:async()=>{throw Error('storage unavailable');}})};
assert.equal((await login()).status,503);
env.MANAGEMENT_SESSIONS=binding;
env.YONETIM_RATE_LIMITER.limit=async()=>({success:false});
assert.equal((await login()).status,429);
env.YONETIM_RATE_LIMITER.limit=async()=>{throw Error('unavailable');};
assert.equal((await login()).status,503);
delete env.YONETIM_PASSWORD;assert.equal((await login()).status,503);
assert.equal((await send('giris',{method:'POST',body:'password=anything'})).headers.get('set-cookie'),null);
const data=new Map();let alarm;
const storage={get:async k=>data.get(k),put:async(k,v)=>data.set(k,v),deleteAll:async()=>data.clear(),setAlarm:async t=>alarm=t};
const store=new ManagementSessions({storage}),fingerprint='a'.repeat(64);
const req=method=>new Request('https://internal/',{method,body:JSON.stringify({fingerprint})});
await store.fetch(req('PUT'));assert.ok(alarm>Date.now());
assert.equal((await new ManagementSessions({storage}).fetch(req('POST'))).status,200,'Survives object restart');
data.get('session').expires=Date.now()-1;
assert.equal((await store.fetch(req('POST'))).status,401,'Expiry is enforced even before cleanup alarm');
await store.alarm();assert.equal(data.size,0);
console.log('PASS: unique management sessions, strong logout revocation, server expiry, rotation, rate limits and fail-closed configuration.');
